searches:
  - name: linkedin-tech-lead-fr-remote
    source: linkedin
    search_url: "https://www.linkedin.com/jobs/search/?currentJobId=4386382859&f_WT=2&geoId=105015875&keywords=tech%20lead&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true"
  - name: linkedin-tech-lead-fr-remote-page-2
    source: linkedin
    search_url: "https://www.linkedin.com/jobs/search/?currentJobId=4380112506&f_WT=2&geoId=105015875&keywords=tech%20lead&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true&start=25"
  - name: linkedin-engineering-manager-fr-remote
    source: linkedin
    search_url: "https://www.linkedin.com/jobs/search/?f_WT=2&geoId=105015875&keywords=engineering%20manager&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true"
  - name: linkedin-team-lead-fr-remote
    source: linkedin
    search_url: "https://www.linkedin.com/jobs/search/?f_WT=2&geoId=105015875&keywords=team%20lead&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true"
  - name: wttj-tech-lead-fr-remote
    source: wttj
    search_url: "https://www.welcometothejungle.com/fr/jobs?refinementList%5Boffices.country_code%5D%5B%5D=FR&refinementList%5Bcontract_type%5D%5B%5D=full_time&refinementList%5Bremote%5D%5B%5D=fulltime&query=tech%20lead&page=1&collections%5B%5D=remote_friendly"
  - name: remotefr-php
    source: remotefr
    search_url: "https://remotefr.com/competences/php/"
  - name: remotefr-java
    source: remotefr
    search_url: "https://remotefr.com/competences/java/"
  - name: remotefr-manager
    source: remotefr
    search_url: "https://remotefr.com/competences/manager/"
  - name: englishjobs-remote
    source: englishjobs
    search_url: "https://englishjobs.fr/jobs/remote"
  - name: doctrine-careers
    source: doctrine
    search_url: "https://www.doctrine.fr/recrutement"
